export const countryOptions = [
  { value: "us", label: "United States", flag: "🇺🇸" },
  { value: "gb", label: "United Kingdom", flag: "🇬🇧" },
  { value: "ca", label: "Canada", flag: "🇨🇦" },
  { value: "fr", label: "France", flag: "🇫🇷" },
  { value: "de", label: "Germany", flag: "🇩🇪" },
  { value: "jp", label: "Japan", flag: "🇯🇵" },
  { value: "it", label: "Italy", flag: "🇮🇹" },
  { value: "es", label: "Spain", flag: "🇪🇸" },
  { value: "cn", label: "China", flag: "🇨🇳" },
  { value: "in", label: "India", flag: "🇮🇳" },
  { value: "au", label: "Australia", flag: "🇦🇺" },
  { value: "br", label: "Brazil", flag: "🇧🇷" },
  { value: "mx", label: "Mexico", flag: "🇲🇽" },
  { value: "za", label: "South Africa", flag: "🇿🇦" },
  { value: "kr", label: "South Korea", flag: "🇰🇷" },
  { value: "se", label: "Sweden", flag: "🇸🇪" },
  { value: "ar", label: "Argentina", flag: "🇦🇷" },
  { value: "ng", label: "Nigeria", flag: "🇳🇬" },
  { value: "nl", label: "Netherlands", flag: "🇳🇱" },
  { value: "no", label: "Norway", flag: "🇳🇴" },
  { value: "ch", label: "Switzerland", flag: "🇨🇭" },
  { value: "at", label: "Austria", flag: "🇦🇹" },
  { value: "be", label: "Belgium", flag: "🇧🇪" },
  { value: "dk", label: "Denmark", flag: "🇩🇰" },
  { value: "fi", label: "Finland", flag: "🇫🇮" },
  { value: "gr", label: "Greece", flag: "🇬🇷" },
  { value: "ie", label: "Ireland", flag: "🇮🇪" },
  { value: "pt", label: "Portugal", flag: "🇵🇹" },
  { value: "pl", label: "Poland", flag: "🇵🇱" },
  { value: "cz", label: "Czech Republic", flag: "🇨🇿" },
  { value: "hu", label: "Hungary", flag: "🇭🇺" },
  { value: "tr", label: "Turkey", flag: "🇹🇷" },
  { value: "il", label: "Israel", flag: "🇮🇱" },
  { value: "eg", label: "Egypt", flag: "🇪🇬" },
  { value: "ua", label: "Ukraine", flag: "🇺🇦" },
  { value: "ro", label: "Romania", flag: "🇷🇴" },
  { value: "bg", label: "Bulgaria", flag: "🇧🇬" },
  { value: "ke", label: "Kenya", flag: "🇰🇪" },
  { value: "gh", label: "Ghana", flag: "🇬🇭" },
  { value: "dz", label: "Algeria", flag: "🇩🇿" },
  { value: "ma", label: "Morocco", flag: "🇲🇦" },
  { value: "pk", label: "Pakistan", flag: "🇵🇰" },
  { value: "id", label: "Indonesia", flag: "🇮🇩" },
  { value: "my", label: "Malaysia", flag: "🇲🇾" },
  { value: "th", label: "Thailand", flag: "🇹🇭" },
  { value: "ph", label: "Philippines", flag: "🇵🇭" },
  { value: "vn", label: "Vietnam", flag: "🇻🇳" },
  { value: "sg", label: "Singapore", flag: "🇸🇬" },
  { value: "hk", label: "Hong Kong", flag: "🇭🇰" },
  { value: "tw", label: "Taiwan", flag: "🇹🇼" },
  { value: "nz", label: "New Zealand", flag: "🇳🇿" },
  { value: "sa", label: "Saudi Arabia", flag: "🇸🇦" },
  { value: "ae", label: "United Arab Emirates", flag: "🇦🇪" },
  { value: "ir", label: "Iran", flag: "🇮🇷" },
  { value: "iq", label: "Iraq", flag: "🇮🇶" },
  { value: "af", label: "Afghanistan", flag: "🇦🇫" },
  { value: "bd", label: "Bangladesh", flag: "🇧🇩" },
  { value: "lk", label: "Sri Lanka", flag: "🇱🇰" },
  { value: "np", label: "Nepal", flag: "🇳🇵" },
  { value: "mm", label: "Myanmar", flag: "🇲🇲" },
  { value: "zm", label: "Zambia", flag: "🇿🇲" },
  { value: "zw", label: "Zimbabwe", flag: "🇿🇼" },
  { value: "cl", label: "Chile", flag: "🇨🇱" },
  { value: "co", label: "Colombia", flag: "🇨🇴" },
  { value: "pe", label: "Peru", flag: "🇵🇪" },
  { value: "ve", label: "Venezuela", flag: "🇻🇪" },
  { value: "uy", label: "Uruguay", flag: "🇺🇾" },
  { value: "bo", label: "Bolivia", flag: "🇧🇴" },
  { value: "ec", label: "Ecuador", flag: "🇪🇨" },
  { value: "py", label: "Paraguay", flag: "🇵🇾" },
  // Add more countries as needed
];
